name: Deployment Workflow Aproval 🚀 Deploy

on:
  workflow_run:
    workflows: ["PHP Composer"]
    types:
      - completed

jobs:
  web-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    needs: approval
    
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.petarungan.my.id
        username: contentftp@petarungan.my.id
        password: ${{ secrets.ftp_password }}
        exclude: |
          **/.git*
          vendor/**
          writable/**
          test/**
          tests/**
          public/**
          .github/**
          .git/**
          git/**

  approval:
      runs-on: ubuntu-latest
      steps:
      - name: Approval Step
        run: echo "Waiting for approval..."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 60 # Set a timeout as needed
  
      - name: Approval Completed
        if: success()
        run: echo "Approval received, proceeding with deployment"
