name: Continuous Integration and Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "fauzan" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate composer.json and composer.lock
        run: composer validate --strict
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Run test suite
        run: composer run-script test

  approval:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Await Approval
        uses: hmarr/await-approval-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: Gitfauzan # Ganti dengan nama pengguna GitHub Anda

  deploy:
    runs-on: ubuntu-latest
    needs: approval
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Get latest code
        uses: actions/checkout@v4
      - name: Sync files to production
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.petarungan.my.id
          username: ftppublic@petarungan.my.id
          password: ${{ secrets.ftp_password }}
          local-dir: ./public/
          exclude: |
            **/.git*
            vendor/**

  web-deploy:
    name: Deploy to web server
    runs-on: ubuntu-latest
    needs: deploy
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Get latest code
        uses: actions/checkout@v4
      - name: Sync files to web server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.petarungan.my.id
          username: contentftp@petarungan.my.id
          password: ${{ secrets.ftp_password }}
          exclude: |
            **/.git*
            vendor/**
            writable/**
            test/**
            tests/**
            public/**
            .github/**
            .git/**
            git/**
