name: Manual Approval

on:
  workflow_run:
    workflows: ["Continuous Integration and Deployment"]
    types:
      - completed

jobs:
  approve-deploy:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Awaiting Approval
        run: echo "Manual approval needed. Please approve this job in the Actions tab."
