name: Continuous Integration and Delivery

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "fauzan" ]

permissions:
  contents: read

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run test suite
        run: |
          composer run-script test

  deploy1:
    name: Deploy to continues delivery1
    runs-on: ubuntu-latest
    needs: build1
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Sync files to production
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.petarungan.my.id
          username: continues_delivery1@petarungan.my.id
          password: ${{ secrets.delivery1 }}
          local-dir: ./lala/
        

  web-deploy1:
    name: Deploy to continues delivery2
    runs-on: ubuntu-latest
    needs: deploy1
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Sync files to web server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.petarungan.my.id
          username: deivery2@petarungan.my.id
          password: ${{ secrets.delivery2 }}
          local-dir: ./lala/
