name: Continuous Intergration and Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "fauzan" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: composer validate --strict
      
     # menyimpan paket Composer yang diunduh ke cache
    - name: menyimpan paket Composer yang diunduh ke cache
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
          
     # menginstal dependensi proyek
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: |
        composer run-script test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
     web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.petarungan.my.id
        username: ftppublic@petarungan.my.id
        password: ${{ secrets.ftp_password }}
        local-dir: ./public/
        exclude: |
          **/.git*
          vendor/**

    deploy:
    runs-on: ubuntu-latest
    needs: web-deploy
    if: github.ref == 'refs/heads/main'

    web-deploy-main:
    name: 🎉 Deploymain
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.petarungan.my.id
        username: contentftp@petarungan.my.id
        password: ${{ secrets.ftp_password }}
        exclude: |
          **/.git*
          vendor/**
          writable/**
          test/**
          tests/**
          public/**
          .github/**
          .git/**
          git/**
          
