name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "fauzan" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4


    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: mbstring, intl, pdo, pdo_mysql
        ini-values: post_max_size=256M, upload_max_filesize=256M, memory_limit=512M
        tools: composer

    - name: Validate composer.json and composer.lock
      run: composer validate --strict
      
     # menyimpan paket Composer yang diunduh ke cache
    - name: menyimpan paket Composer yang diunduh ke cache
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
          
     # menginstal dependensi proyek
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run test suite
      run: |
        composer run-script test
        
    - name: Run tests
      run: php spark test
        
